[2024-09-28T01:58:14.808+0000] {processor.py:186} INFO - Started process (PID=6171) to work on /opt/airflow/dags/etl_dag.py
[2024-09-28T01:58:14.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-09-28T01:58:14.812+0000] {logging_mixin.py:190} INFO - [2024-09-28T01:58:14.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-09-28T01:58:14.858+0000] {logging_mixin.py:190} INFO - [2024-09-28T01:58:14.851+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 4, in <module>
    from AsteroidsNearEarth_ETL import main_etl_asteriods_near_earth
ModuleNotFoundError: No module named 'AsteroidsNearEarth_ETL'
[2024-09-28T01:58:14.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-09-28T01:58:14.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.095 seconds
[2024-09-28T01:58:45.114+0000] {processor.py:186} INFO - Started process (PID=6230) to work on /opt/airflow/dags/etl_dag.py
[2024-09-28T01:58:45.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-09-28T01:58:45.119+0000] {logging_mixin.py:190} INFO - [2024-09-28T01:58:45.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-09-28T01:58:45.162+0000] {logging_mixin.py:190} INFO - [2024-09-28T01:58:45.152+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 4, in <module>
    from AsteroidsNearEarth_ETL import main_etl_asteriods_near_earth
ModuleNotFoundError: No module named 'AsteroidsNearEarth_ETL'
[2024-09-28T01:58:45.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-09-28T01:58:45.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.080 seconds
[2024-09-28T01:59:15.656+0000] {processor.py:186} INFO - Started process (PID=6294) to work on /opt/airflow/dags/etl_dag.py
[2024-09-28T01:59:15.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-09-28T01:59:15.662+0000] {logging_mixin.py:190} INFO - [2024-09-28T01:59:15.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-09-28T01:59:15.709+0000] {logging_mixin.py:190} INFO - [2024-09-28T01:59:15.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 4, in <module>
    from AsteroidsNearEarth_ETL import main_etl_asteriods_near_earth
ModuleNotFoundError: No module named 'AsteroidsNearEarth_ETL'
[2024-09-28T01:59:15.713+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-09-28T01:59:15.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.098 seconds
[2024-09-28T01:59:45.828+0000] {processor.py:186} INFO - Started process (PID=6357) to work on /opt/airflow/dags/etl_dag.py
[2024-09-28T01:59:45.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-09-28T01:59:45.831+0000] {logging_mixin.py:190} INFO - [2024-09-28T01:59:45.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-09-28T01:59:45.847+0000] {logging_mixin.py:190} INFO - [2024-09-28T01:59:45.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 4, in <module>
    from AsteroidsNearEarth_ETL import main_etl_asteriods_near_earth
ModuleNotFoundError: No module named 'AsteroidsNearEarth_ETL'
[2024-09-28T01:59:45.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-09-28T01:59:45.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.051 seconds
[2024-09-28T02:00:16.309+0000] {processor.py:186} INFO - Started process (PID=6420) to work on /opt/airflow/dags/etl_dag.py
[2024-09-28T02:00:16.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-09-28T02:00:16.313+0000] {logging_mixin.py:190} INFO - [2024-09-28T02:00:16.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-09-28T02:00:16.348+0000] {logging_mixin.py:190} INFO - [2024-09-28T02:00:16.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 4, in <module>
    from AsteroidsNearEarth_ETL import main_etl_asteriods_near_earth
ModuleNotFoundError: No module named 'AsteroidsNearEarth_ETL'
[2024-09-28T02:00:16.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-09-28T02:00:16.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.071 seconds
[2024-09-28T02:00:46.636+0000] {processor.py:186} INFO - Started process (PID=6483) to work on /opt/airflow/dags/etl_dag.py
[2024-09-28T02:00:46.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-09-28T02:00:46.639+0000] {logging_mixin.py:190} INFO - [2024-09-28T02:00:46.638+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-09-28T02:00:46.699+0000] {logging_mixin.py:190} INFO - [2024-09-28T02:00:46.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 4, in <module>
    from AsteroidsNearEarth_ETL import main_etl_asteriods_near_earth
ModuleNotFoundError: No module named 'AsteroidsNearEarth_ETL'
[2024-09-28T02:00:46.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-09-28T02:00:46.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.095 seconds
[2024-09-28T02:01:16.959+0000] {processor.py:186} INFO - Started process (PID=6546) to work on /opt/airflow/dags/etl_dag.py
[2024-09-28T02:01:16.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-09-28T02:01:16.962+0000] {logging_mixin.py:190} INFO - [2024-09-28T02:01:16.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-09-28T02:01:16.995+0000] {logging_mixin.py:190} INFO - [2024-09-28T02:01:16.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 4, in <module>
    from AsteroidsNearEarth_ETL import main_etl_asteriods_near_earth
ModuleNotFoundError: No module named 'AsteroidsNearEarth_ETL'
[2024-09-28T02:01:16.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-09-28T02:01:17.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.074 seconds
[2024-09-28T02:01:32.778+0000] {processor.py:186} INFO - Started process (PID=6560) to work on /opt/airflow/dags/etl_dag.py
[2024-09-28T02:01:32.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2024-09-28T02:01:32.783+0000] {logging_mixin.py:190} INFO - [2024-09-28T02:01:32.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2024-09-28T02:01:32.835+0000] {logging_mixin.py:190} INFO - [2024-09-28T02:01:32.829+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 200, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'star_date'
[2024-09-28T02:01:32.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2024-09-28T02:01:32.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.090 seconds
